### ISSUE TITLE
Minor inconsistencies on page /software/applications/pytorch.html

### ISSUE THREAD

**Issue by tsrobinson** [N8-CIR-Bede/documentation#146]
Thanks for these guides, they are super useful!

The PyTorch guide notes `... the following instructions can be used to create a Python **3.9** conda environment named **torch** with the latest Open-CE provided PyTorch' [emphasis added].

This is inconsistent with the code at present, which instantiates a conda env with Python=3.**8** called torch**-env**

I will submit a pull request for this issue.

**Comment by ptheywood** [comment]
Closed by #147. Thanks for the contributon!
