### ISSUE TITLE
Explore Satori documentation

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#15]
Have a look at https://mit-satori.github.io/ and see what we can learn from them.

**Comment by Fehings** [comment]
Some ideas from the Satori docs:
- They have a training page with vimeo links to videos that give generic training on GPU computing (mainly NVIDIA ones), could we link to these same or other similar open source content to give users some initial pointers? Would it be possible to make any of the IBM training ones they gave for Bede users available online to link to?

- They have some great 'how-to' guides for R and julia with example batch scripts which would be nice to emulate. Perhaps the easiest thing would be to follow the Satori guides on Bede and see if they hold for Bede, and if so cannibalise these for Bede (giving credit to Satori and not word for word I mean).

- They have a troubleshooting tips section, which I think would be a nice feature for us to add to enable users to do some initial checks themselves before contacting RSE support.

- There is a section on tools for copying large files which again we could cannibalise assuming these tools will work just the same on Bede.

- They have an acceptable use/ code of conduct section which would be an easy addition for us, there is mention already in the Using Bede section about not spamming the login node and not storing personal data, etc, but we could replicate these notes in a separate section as well so they are not buried in the rest of the text.

**Comment by markdturner** [comment]
Too open-ended a task, will be used as reference for more specific issues
