### ISSUE TITLE
MFA - clarify separate TOTP for safe.epcc.ac.uk and bede login

### ISSUE THREAD

**Issue by ptheywood** [N8-CIR-Bede/documentation#159]
It may be worth explicitly stating that the MFA on Bede is not the same MFA as the general EPCC SAFE MFA (which users are required to have to get accounts on Bede).

**Comment by ptheywood** [comment]
EPCC Safe dones't require 2FA to be enabled, but presumably it's encouragaed somwhere

Relevant epcc docs:

https://epcced.github.io/safe-docs/safe-for-users/#2fac

**Comment by bodgerer** [comment]
Also need to add emphasis on accessibility being a particular reason you may need alternative options.

**Comment by bodgerer** [comment]
Also need to emphasis what to do if MFA token is lost (ask for password reset in SAFE)

**Comment by ptheywood** [comment]
Closed by #160
