### ISSUE TITLE
note manual account creation

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#197]
I don't know if anyone's paying attention now, but I've had several people expecting to be able to log in as soon as they've done the account thing in SAFE.  The doc should say that creating the account is a manual process, and to wait for mail about it.  (I assume they get mail.)

**Comment by ptheywood** [comment]
I recieved an email via SAFE (in 2020) titled 

> Your new account for <USERNAME> on Bede has been created

Which stating (among other bits)

> Your request for a  machine account has been approved by your
> Principal Investigator and the account has now been created. 

I'd assume that is still the case but not 100%. 

I'll add a bullet to the `Registering` section of the usage page mentioning it.
