### ISSUE TITLE
working profiling instructions needed

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#20]
I asked about this on the list with no response.  Can an expert provide working profiling instructions?  When I tried running nsys as documented, it crashed on startup, apparently trying to execute the target binary.  Following material from OLCF, I tried nv-nsight-cu-cli.  That at least ran, though it didn't produce any events -- quite likely because it's now failing to touch the GPU for some reason I'll have to investigate.

**Comment by ptheywood** [comment]
I've just tested `nsys` provided by the `nsight-systems/2020.3.1` module on a simple test applicaiton and it successfully generated the profiler report, suggesting it may be specific to the binary beign profiled.

`ncu` from `nsight-compute/2020.2.1` captured kernel profiling information too. 

I'll update the info on the docs which are now out of date like the module names etc, but i'm not sure what to suggest about the issue you are encountering. 
There are more recent versions of the profilers than available on Bede currently, which may fix internal issues within the profilers.

**Comment by loveshack** [comment]
For what it's worth, the crash appears to be due to using LD_PRELOAD.

(It looks as if this should come with a health warning.  DGEMM ran a
factor of four slower under nsys using default flags other than
-t cuda,nvtx,openmp,osrt.)
