### ISSUE TITLE
CI doesn't work on PRs

### ISSUE THREAD

**Issue by alisonrclarke** [N8-CIR-Bede/documentation#25]
Need to ensure the CI knows how to check out the right version of the code.

(Suspect this is an issue with the [readthedocs action](https://github.com/DavidLeoni/readthedocs-to-actions) but I think it should be solvable by passing the right parameters to the action.)

**Comment by alisonrclarke** [comment]
The GitHub Checkout action uses:

```
/usr/bin/git checkout --progress --force refs/remotes/pull/24/merge
```

but the readthedocs action tries to run:

```
git checkout --force origin/merge
```

(where `merge` comes from the `VERSION` parameter to the step.

**Comment by willfurnass** [comment]
If it helps, we're using this GHA workflow for PRs against U. Sheffield's Sphinx-based HPC docs: https://github.com/rcgsheffield/sheffield_hpc/blob/master/.github/workflows/pull-request.yml

**Comment by alisonrclarke** [comment]
Thanks @willfurnass . The issue with the Sphinx action is that it runs a newer version of Sphinx than readthedocs, so it tries to run a command that doesn't work with the one specified in our conf.py (which was deliberately set up to try to mimic readthedocs).

**Comment by willfurnass** [comment]
@alisonrclarke Ah, we'll need to be mindful of that issue with our U. Sheffield docs then!

**Comment by alisonrclarke** [comment]
Realised that easiest thing to do is just build the docs using python/sphinx rather than using an over-complex action. See #29

**Comment by ptheywood** [comment]
#29 has resolved this.
