### ISSUE TITLE
Create a glossary

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#26]

**Comment by markdturner** [comment]
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

**Comment by markdturner** [comment]
Place a file called `index.rst` in a folder called `glossary`. Ensure the link is added to the main site navigation.

**Comment by ptheywood** [comment]
Closing as #64 has been merged, and #69 is a list of terms to add to the glossary.
