### ISSUE TITLE
Add Bede entry to UK HPC Facilities website

### ISSUE THREAD

**Issue by bodgerer** [N8-CIR-Bede/documentation#31]
We need to add Bede to the website containing the list of UK Tier1/2 HPC facilities.

https://www.hpc-uk.ac.uk/facilities/

To be done via github pull request here https://github.com/hpc-uk/hpcuk-website/fork/

**Comment by ptheywood** [comment]
This can be closed once https://github.com/hpc-uk/hpcuk-website/pull/16 has been accepted and merged.

**Comment by ptheywood** [comment]
This has now been merged into the hpc-uk website.
