### ISSUE TITLE
support addresses

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#35]
The documentation should have (a pointer to?) the support addresses somewhere that's easy to spot.  I guess it should be a link to them on n8cir.org.uk, if that's authoritative.

**Comment by Fehings** [comment]
Will add this to the FAQ's as a 'how can I get further help?' question and link to the list of RSE emails. Assuming that would fit the bill, Dave?

**Comment by loveshack** [comment]
> Will add this to the FAQ's as a 'how can I get further help?' question
> and link to the list of RSE emails. Assuming that would fit the bill,
> Dave?

I'd have thought it's more than an FAQ, but as long as it goes
somewhere.  I suppose to avoid information diverging in two places it
should be a link to the main site.
