### ISSUE TITLE
Add Gromacs Info

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#37]
For the time being, we use the hecbiosim module for gromacs, which is made available by the command "module load hecbiosim gromacs" . 

This info should be added under "Software". Very important: credits and thanks to HECBioSim for allowing us to use it!

**Comment by markdturner** [comment]
Waiting for GROMACS group to produce documentation.

**Comment by ptheywood** [comment]
Will add a stub of a page during #67 pointing to the hecbiosim module, with room for further information to be added via the gromacs bede taskforce at a later date.
