### ISSUE TITLE
NCCL/nvhpc

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#41]
I had a user who wanted NCCL and thought they needed to install it.  I don't know whether users should know about nvhpc and getting NCCL from it, but I didn't, so it presumably needs documenting.  I needed find(1) to locate libnccl.
It's not obvious to non-experts what nvhpc is and why you'd want it, other than for any other libraries that are only there.  (The compiler generates significantly worse code than GCC on what I've measured.)

**Comment by Fehings** [comment]
Need to add nvhpc and nvcc (etc.) to compiler docs and to link to actual docs for these.
