### ISSUE TITLE
Containers / Singularity 

### ISSUE THREAD

**Issue by ptheywood** [N8-CIR-Bede/documentation#49]
Document the use of containers on Bede via Singularity. 

On RHEL 7 this is a module. 
On RHEL 8 it is natively installed.

+ [ ] Basic description + usage instructions (module / availability)
+ [ ] Expand with worked example(s) of use

**Comment by willfurnass** [comment]
Is that the latest available version?  3.7.4 and 3.7.3 contained security fixes: https://github.com/hpcng/singularity/releases

**Comment by loveshack** [comment]
It's quite a job keeping up with Singularity churn, though EPEL currently has 3.8.
I understood SUSE looked at it and went with Charliecloud, which I wrote up as a solution particularly for unprivileged builds (as well as runtime).

**Comment by ptheywood** [comment]
For reference, Singularity is now part of the linux foundation and has been rebranded as Apptainer.

For now, in #67 I've mentioned this so it brings up the singularity page via anyone searching for apptainer. So far it looks like commands are still `singularity`, and hopefully they will maintain this going forwards.
