### ISSUE TITLE
Refactor documentation structure

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#5]
The documentation, as currently in this repository's wiki, is one long piece of text. When transferred over to the website, it would make sense to give it a better structure to improve readability and accessibility

**Comment by alisonrclarke** [comment]
The Software page is currently getting a little bloated (and will be more so once PR #27 is merged). I'd suggest breaking it down into subpages but trying to work out the best structure.

Thinking about something like:

- Environments
- Compilers
- (BLAS/LAPACK, MPI, HDF5, NetCDF - do they form any sort of grouping? They're just all short sections)
- Python
- CUDA (or does that belong elsewhere?)

Should WMLCE stuff also be separate?

**Comment by MarionBWeinzierl** [comment]
Sounds good!

WMLCE should somehow go into a separate page with a large disclaimer at the top, stating that it will not longer be supported, I'd say. And then we probably need an OpenCE page to refer to for as replacement.
