### ISSUE TITLE
Matlab alternatives

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#56]
There's an FAQ about the absence of Matlab.  If people really want that sort of thing, GNU Octave and Scilab can be built on ppc64le.  You speed up large-scale linear algebra (and possibly FFTs) by preloading ESSL or making a compatible shim, as with R.  However, performance is disappointing and I didn't get information on improving it.  There's also MPI support, at least for Octave.

**Comment by Fehings** [comment]
Including a comment in the Matlab FAQ that it is possible to install Octave on Bede.

**Comment by loveshack** [comment]
If it is wanted, the EPEL8 rpm should probably be installed.  That's
reasonably recent, unlike EPEL7.
