### ISSUE TITLE
Document how to use Amber

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#78]
Talk to James Gebbie about access to Amber and add the info to the docs

**Comment by ptheywood** [comment]
#67 adds very basic amber docs, at `software/applications/amber.rst`. 

Additional, more detailed docs can be added to this file once it has been approved and merged on actual amber use (ideally by someone who has used amber)

**Comment by ptheywood** [comment]
Now #67 is merged, the very basic Amber documentation can be exapended by editing [software/applications/amber.rst](https://github.com/N8-CIR-Bede/documentation/blob/main/software/applications/amber.rst)
