### ISSUE TITLE
Document how to use Gromacs

### ISSUE THREAD

**Issue by MarionBWeinzierl** [N8-CIR-Bede/documentation#79]
Talk to James Gebbie about how to use Gromacs and add the information to the docs

**Comment by ptheywood** [comment]
I've added some basic Gromacs documentation in PR #67. 

This is also a duplicate of #37.

**Comment by ptheywood** [comment]
Now #67 is merged, the very basic Gromacs documentation can be exapended by editing [software/applications/gromacs.rst](https://github.com/N8-CIR-Bede/documentation/blob/main/software/applications/gromacs.rst)

**Comment by ptheywood** [comment]
Closing this as the docs taskforce is being closed. The docs page can still be expanded if required with bede-speicifc additions if required.
