### ISSUE TITLE
Switch to (branded) alternate sphinx theme

### ISSUE THREAD

**Issue by ptheywood** [N8-CIR-Bede/documentation#87]
While working on splitting the source / using `toctree` more heavily, issues with the sphinx-bootstrap theme have been cropping up that are hard to workaround, or are not trivial to resolve.

This includes:

+ The width of the sidebar being limited, resulting in small text and empty margin
+ Sidebar current entry highlighting for in-page content is not implemented (requires css + js) 
+ Hard to read `<pre>` content
+ Hard to read content in `info` and `warning` blocks, which are difficult to restyle without changing the theme (Bold colours are good for headers, but make reading longer text more difficult)
+ Navbar hiding content (#80)

Many of these would be resolved by switching to the `sphinx-rtd-theme`, with rebranding of colours. 

This is essentially duplicating previous work, but it should be less effort than manually modifying the sphinx-bootstrap-theme to address the issues highlighted above.

As other potential alternative themes, [furo](https://github.com/pradyunsg/furo) and [pydata-sphinx-them](https://github.com/pydata/pydata-sphinx-theme) are potential alternatives 

If any big theme changes are made, it would also be worthwhile ensuring accessibility guideleines are met (#42)

**Comment by ptheywood** [comment]
Some testing of other sphinx themes without significant branding for reference, to see if they resolve the issues above. Further branding would be possible if the switch is deemed worthwhile.


## sphinx-rtd-theme

![image](https://user-images.githubusercontent.com/628937/151843674-ea8a2cc9-4086-400c-948f-de8ced497f42.png)


## furo

Furo has a user-toggleable dark and light theme, It should be possible to configure the default or disable this if it complicates and custom css.

### Light

![image](https://user-images.githubusercontent.com/628937/151844036-9042ec15-1854-4dd4-97fa-b0864b7a6105.png)


### Dark

![image](https://user-images.githubusercontent.com/628937/151843981-f1fbf870-dda5-46e4-b7cb-19b67ec1195f.png)


## pydata

![image](https://user-images.githubusercontent.com/628937/151843860-f9eb6158-84a3-4215-8dc5-2d1ff0a6a05b.png)

**Comment by markdturner** [comment]
Furo looks the best if it can be made to include in-page navigation.

**Comment by ptheywood** [comment]
Furo's developer / maintainer has marked issues for combining the site navigation and page navigation into a single sidebar as `wontfix`, as it is intended to be separate. 

https://github.com/pradyunsg/furo/issues/79

I'm not convinced the split site and page toc is the better option, especially when both fold/collapse independently so the second toc may not be found by users.

We could probably override furo's toc implementation to include the page navigation, but this might be a decent amount of effort, so I'll likely fallback to `rtd-theme` unfortunately.

**Comment by ptheywood** [comment]
### Material theme

A few other HPC centres (Archer2, baskerville) use `mkdocs` based documentation with the `Material` theme.
There is a sphinx port of this theme, which splits the navigation and page content like Furo, but does not fold the in-page nav as aggressively. 

![image](https://user-images.githubusercontent.com/628937/157497605-f97b2948-cc4a-4f04-babc-4f0f6f2d985f.png)

However it does fold the site navigation quite early, and the mobile navigation lackas any indication of depth:

![image](https://user-images.githubusercontent.com/628937/157497717-3e672f69-eec7-4389-962f-6d2082054da3.png)

It is not clearly under development/active maintenance however.

## Sphinx-book-theme

The sphinx book theme mentioned in the previous comment seems like a good option for a non-RTD theme which splits the navigation and in-page tocs. 

![image](https://user-images.githubusercontent.com/628937/157498202-5d45fe05-85f4-407a-9a1e-5f1710214a17.png)



My only real complaint so far is the in-page highlighting of the current element does not behave well with short sections, as it skips some headings depending on content length. 

I.e. the `Installing Conda Packages` section is never actively highlighted

![image](https://user-images.githubusercontent.com/628937/157498837-47666c22-fa3d-4fa9-9e4d-f455ec3f65f5.png)

I'd also like the topbar to include the n8cir logo when the side-nav is folded away, but i've not looked into this yet. 

I'll spend a short amount of time customising/branding `sphinx-rtd-theme` and `sphinx-book-theme` to see how they look with branding, then potentially reach out for feedback on which option is prefferred unless a clear winner arises.

**Comment by ptheywood** [comment]
Simple customisation of the sphinx-book-theme, pushed to `theme-test-book`. 

If selected over RTD, there's still a bit more work to be done

+ Run it through accessibililty toools
  + Likely requires the orange changing
+ The page footer states `By N8 CIR` which is redundent, this might need the footer theme template overriding. 
  + It would also be good to add the `Made with sphinx, using the sphinx-book-theme` text for attribution (not required but a good thing to do).
+ The link in the annoucement text is not an actual destination yet, and can't use `:ref:` in `conf.py`
+ Codeblock styling
+ Testing with RTD extensions (version selector, ethical ads)

So far switching to this has greatly reduced the amount of custom CSS required to workaround issues, and fixes the major problems with the boostrap theme highlighted at the start of this issue.

![image](https://user-images.githubusercontent.com/628937/157523932-a31917cc-3ac8-4332-b322-fc157363171d.png)

**Comment by ptheywood** [comment]
I've set up temporary hosted demos of the RTD and book themes via ghpages + repo forks for demos withotu local builds being required:


+ `sphinx-book-theme`: https://ptheywood.uk/bede-docs-demo-book/
+ `sphinx-rtd-theme`: https://ptheywood.uk/bede-docs-demo-rtd/
+ Current: https://bede-documentation.readthedocs.io/
